Readme file update
HibiAdelei/myspot pull request #79
Opened 2021-08-01 22:55 UTC by wooglow

Not finished yet

2021-08-01 23:25 UTC, LemonPocky requested changes

2021-08-01 23:25 UTC, LemonPocky commented on README.md
> +# Note Maker App
MySpot

2021-08-01 23:27 UTC, wooglow reviewed
OKay fixed

2021-08-02 01:36 UTC, LemonPocky approved these changes

2021-08-02 01:36 UTC, merged